version: "3.8"
services:
  webserver:
    container_name: "webserver"
    build: .
    image: webserver:latest
    command: npm start
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./src:/webserver/src
    env_file:
      - webserver.env
    depends_on:
      - "postgres"
  postgres:
    container_name: "postgres"
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
